import React from 'react';
import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Section,
  Text,
  Hr,
  Button,
} from '@react-email/components';

interface WaterBarFollowupProps {
  customerName: string;
  consumedCount: number;
  consumedDrinks: string[];
  remainingDrinks: string[];
  totalDrinks: number;
  advice: string;
  orderId?: string;
}

export default function WaterBarFollowup({
  customerName = 'Hydration Enthusiast',
  consumedCount = 1,
  consumedDrinks = ['Water'],
  remainingDrinks = [],
  totalDrinks = 1,
  advice = 'Great job staying hydrated!',
  orderId,
}: WaterBarFollowupProps) {
  const isComplete = remainingDrinks.length === 0;
  const trackerUrl = orderId ? `https://thewater.bar/?tracking_order_id=${orderId}` : null;

  return (
    <Html>
      <Head />
      <Preview>
        {isComplete
          ? "🎉 You've completed your hydration journey!"
          : `Keep up the hydration! ${remainingDrinks.length} drinks remaining`}
      </Preview>
      <Body style={main}>
        <Container style={container}>
          {/* Header */}
          <Section style={header}>
            <Heading style={h1}>{isComplete ? '🎉 Hydration Complete!' : '💧 Keep Hydrating!'}</Heading>
            <Text style={headerSubtext}>Personalized by AI, just for you</Text>
          </Section>

          {/* Content */}
          <Section style={content}>
            <Text style={greeting}>Hi {customerName},</Text>

            <Text style={paragraph}>
              {isComplete
                ? `Amazing! You've consumed all ${totalDrinks} of your drinks. Your hydration journey is complete for today!`
                : `Great progress! You've consumed ${consumedCount} of your ${totalDrinks} drinks.`}
            </Text>

            {/* Consumed Drinks */}
            {consumedDrinks.length > 0 && (
              <Section style={drinkSection}>
                <Heading style={sectionHeading}>✅ Drinks Consumed</Heading>
                {consumedDrinks.map((drink, index) => (
                  <Text key={index} style={drinkItem}>
                    • {drink}
                  </Text>
                ))}
              </Section>
            )}

            {/* Remaining Drinks */}
            {remainingDrinks.length > 0 && (
              <Section style={drinkSection}>
                <Heading style={sectionHeading}>🥤 Don't Forget</Heading>
                {remainingDrinks.map((drink, index) => (
                  <Text key={index} style={drinkItem}>
                    • {drink}
                  </Text>
                ))}
              </Section>
            )}

            {/* Completion Badge */}
            {isComplete && (
              <Section style={completionBadge}>
                <Text style={completionText}>🏆 Hydration Goal Achieved!</Text>
                <Text style={completionSubtext}>You've completed your hydration journey for today</Text>
              </Section>
            )}

            {/* AI Advice */}
            <Section style={adviceSection}>
              <Heading style={adviceHeading}>💡 Your Personalized Advice</Heading>
              <Text style={adviceText}>{advice}</Text>
            </Section>

            <Hr style={hr} />

            {/* Pro Tips */}
            <Section style={tipsSection}>
              <Heading style={tipsHeading}>🎯 Pro Hydration Tips</Heading>
              <Text style={tipItem}>• Start your day with 500ml of water</Text>
              <Text style={tipItem}>• Drink before you feel thirsty</Text>
              <Text style={tipItem}>• Monitor urine color - aim for pale yellow</Text>
              <Text style={tipItem}>• Herbal teas and water-rich foods count too!</Text>
            </Section>

            {/* CTA Buttons */}
            <Section style={ctaSection}>
              {trackerUrl && !isComplete && (
                <Button
                  style={{ ...button, marginBottom: '12px' }}
                  href={trackerUrl}
                >
                  📱 Update My Tracker
                </Button>
              )}
              <Button
                style={button}
                href="https://api.whatsapp.com/send?phone=442081336235&text=Hi%20Water%20Bar!%20I%27d%20love%20to%20share%20feedback"
              >
                💬 Share Feedback on WhatsApp
              </Button>
            </Section>

            <Text style={disclaimer}>
              This advice was generated by The Water Bar's AI Hydration Coach based on your order and real-time data.
            </Text>
          </Section>

          {/* Footer */}
          <Section style={footer}>
            <Text style={footerText}>🌊 The Water Bar - Personalized Hydration Solutions</Text>
            <Text style={footerText}>
              <a href="https://www.instagram.com/thewaterbarglobal/" style={footerLink}>
                Follow us on Instagram
              </a>
            </Text>
            <Text style={footerText}>© 2025 | The Water Bar | Dubai, UAE</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '0',
  marginTop: '20px',
  marginBottom: '20px',
  maxWidth: '600px',
  border: '1px solid #e0e0e0',
  borderRadius: '8px',
  overflow: 'hidden',
};

const header = {
  background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  color: '#ffffff',
  padding: '30px 20px',
  textAlign: 'center' as const,
};

const h1 = {
  color: '#ffffff',
  fontSize: '28px',
  fontWeight: 'bold',
  margin: '0',
};

const headerSubtext = {
  color: '#ffffff',
  fontSize: '16px',
  margin: '10px 0 0 0',
  opacity: 0.9,
};

const content = {
  padding: '30px 20px',
};

const greeting = {
  fontSize: '16px',
  lineHeight: '1.6',
  color: '#525f7f',
  marginTop: '0',
};

const paragraph = {
  fontSize: '16px',
  lineHeight: '1.6',
  color: '#525f7f',
};

const drinkSection = {
  backgroundColor: '#f0f8ff',
  padding: '20px',
  borderRadius: '8px',
  margin: '20px 0',
};

const sectionHeading = {
  color: '#0369a1',
  fontSize: '18px',
  fontWeight: '600',
  marginTop: '0',
  marginBottom: '12px',
};

const drinkItem = {
  color: '#075985',
  fontSize: '15px',
  margin: '8px 0',
  lineHeight: '1.4',
};

const completionBadge = {
  backgroundColor: '#f0f9ff',
  border: '2px solid #0ea5e9',
  borderRadius: '8px',
  padding: '20px',
  margin: '20px 0',
  textAlign: 'center' as const,
};

const completionText = {
  fontSize: '20px',
  fontWeight: '600',
  color: '#0ea5e9',
  margin: '0 0 8px 0',
};

const completionSubtext = {
  color: '#666',
  fontSize: '14px',
  margin: '0',
};

const adviceSection = {
  backgroundColor: '#e8f5e8',
  padding: '20px',
  borderRadius: '8px',
  margin: '20px 0',
};

const adviceHeading = {
  color: '#166534',
  fontSize: '18px',
  fontWeight: '600',
  marginTop: '0',
  marginBottom: '12px',
};

const adviceText = {
  color: '#15803d',
  fontSize: '15px',
  lineHeight: '1.6',
  margin: '0',
};

const hr = {
  border: 'none',
  borderTop: '1px solid #e0e0e0',
  margin: '20px 0',
};

const tipsSection = {
  backgroundColor: '#fef3c7',
  padding: '20px',
  borderRadius: '8px',
  margin: '20px 0',
};

const tipsHeading = {
  color: '#92400e',
  fontSize: '18px',
  fontWeight: '600',
  marginTop: '0',
  marginBottom: '12px',
};

const tipItem = {
  color: '#a16207',
  fontSize: '14px',
  margin: '8px 0',
  lineHeight: '1.6',
};

const ctaSection = {
  textAlign: 'center' as const,
  margin: '30px 0',
};

const button = {
  backgroundColor: '#25D366',
  borderRadius: '6px',
  color: '#fff',
  fontSize: '16px',
  fontWeight: 'bold',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '12px 24px',
};

const disclaimer = {
  fontSize: '14px',
  color: '#6b7280',
  textAlign: 'center' as const,
  fontStyle: 'italic',
  margin: '20px 0',
};

const footer = {
  textAlign: 'center' as const,
  padding: '20px',
  backgroundColor: '#f9fafb',
};

const footerText = {
  fontSize: '12px',
  color: '#6b7280',
  margin: '5px 0',
};

const footerLink = {
  color: '#007ee6',
  textDecoration: 'none',
};
