# Fly.io configuration for Email Agent (Background Worker)
app = 'waterbar-email-agent'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile.email-agent'

[env]
  NODE_ENV = 'production'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

# Fly.io automatically restarts crashed apps
# Secrets to set via CLI:
# fly secrets set NEXT_PUBLIC_SUPABASE_URL="https://dpaciwcnzwyymjmkftrc.supabase.co"
# fly secrets set SUPABASE_SERVICE_ROLE_KEY="your-service-role-key"
# fly secrets set ANTHROPIC_API_KEY="your-anthropic-key"
# fly secrets set RESEND_API_KEY="your-resend-key"
