# Fly.io config for Email Follow-Up Agent
# Lightweight autonomous agent (NO HTTP server, pure Realtime listener)

app = 'waterbar-email-agent'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile.email'

[env]
  PYTHONUNBUFFERED = '1'

# Secrets to set via: fly secrets set KEY=value
# Required secrets:
#   - SUPABASE_URL
#   - SUPABASE_SERVICE_ROLE_KEY  
#   - OPENAI_API_KEY
#   - WATERBAR_MCP_PATH=/app/mcp-waterbar-emails/build/index.js
#   - RESEND_API_KEY

[[vm]]
  memory = '512mb'  # Lightweight - no LiveKit!
  cpu_kind = 'shared'
  cpus = 1

# IMPORTANT: Email agent has NO HTTP server
# It's a pure Realtime listener that runs 24/7
# Fly.io requires SOME way to keep it alive, so we use processes

[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 8080  # Dummy port - not actually used

  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# Note: The agent doesn't actually listen on this port,
# but Fly.io needs it defined to keep the machine running
